### ISSUE TITLE
Import apps button broken

### ISSUE THREAD

**Issue by mak448a** [Bonnie39/TrollAppsRepoCreator#2]
When I link to a githubusercontent.com link and click import json, it doesn't fill out the fields in the GUI.

**Comment by Bonnie39** [comment]
Can you provide the link you tried using?

**Comment by mak448a** [comment]
Sure, https://raw.githubusercontent.com/mak448a/repo/main/repo.json

**Comment by Bonnie39** [comment]
The issue isn't with TrollAppsRepoCreator but rather with that specific source. in the screenshots[] for app YTLitePlus, the final screenshot is followed by a comma which causes an error with the json as the last item in a list cannot be followed by a comma.

`"screenshotURLs": [
                "https://raw.githubusercontent.com/YTLitePlus/Assets/main/Screenshots/1.png",
                "https://raw.githubusercontent.com/YTLitePlus/Assets/main/Screenshots/2.png",
                "https://raw.githubusercontent.com/YTLitePlus/Assets/main/Screenshots/3.png",
                "https://raw.githubusercontent.com/YTLitePlus/Assets/main/Screenshots/4.png",
                "https://raw.githubusercontent.com/YTLitePlus/Assets/main/Screenshots/5.png",
                "https://raw.githubusercontent.com/YTLitePlus/Assets/main/Screenshots/6.png",
                "https://raw.githubusercontent.com/YTLitePlus/Assets/main/Screenshots/7.png",
                "https://raw.githubusercontent.com/YTLitePlus/Assets/main/Screenshots/8.png",
                "https://raw.githubusercontent.com/YTLitePlus/Assets/main/Screenshots/9.png",
            ]`
            
screenshot '9.png' shouldn't have a comma after the quotes

**Comment by mak448a** [comment]
Thanks!
